name: Build

on:
  push:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: asdf-vm/actions/install@v1
      - run: spago build --path example/**/*.purs
      - run: spago test
      - run: for example in $(ls example); do spago run -m Example.${example%.*} -p example/$example; done
